---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/collections":
    get:
      summary: Get all collections
      tags:
      - Collections
      responses:
        '200':
          description: Get all comments
  "/api/v1/collections/{collection_id}/{by_user_id}":
    delete:
      summary: Delete a collection
      tags:
      - Collections
      parameters:
      - name: collection_id
        in: path
        required: true
        schema:
          type: string
      - name: by_user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Deleted collection
  "/api/v1/comments":
    get:
      summary: Get all comments
      tags:
      - Comments
      responses:
        '200':
          description: Get all comments
    post:
      summary: Create new comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: Create new comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                user_id:
                  type: integer
                course_id:
                  type: integer
              required:
              - user_id
              - content
              - course_id
            examples:
              example:
                summary: Request example description
                value:
                  content: Foo
                  user_id: 1
                  course_id: 2
  "/api/v1/comments/course/{course_id}":
    get:
      summary: Get all course comments
      tags:
      - Comments
      parameters:
      - name: course_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get all course comments
  "/api/v1/comments/last_week":
    get:
      summary: Get new user information for the week
      tags:
      - Comments
      responses:
        '200':
          description: Get new user information for the week
  "/api/v1/comments/total":
    get:
      summary: Total comments
      tags:
      - Comments
      responses:
        '200':
          description: Total comments
  "/api/v1/comments/{comment_id}/{by_user_id}":
    delete:
      summary: Delete a comment
      tags:
      - Comments
      parameters:
      - name: comment_id
        in: path
        required: true
        schema:
          type: string
      - name: by_user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Deleted comment
  "/api/v1/courses":
    get:
      summary: Get all courses
      tags:
      - course
      responses:
        '200':
          description: Get all courses
  "/api/v1/courses/{course_id}/{by_user_id}":
    delete:
      summary: delete a course
      tags:
      - course
      parameters:
      - name: course_id
        in: path
        required: true
        schema:
          type: string
      - name: by_user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: course deleted
  "/api/v1/notices":
    get:
      summary: Get all notice
      tags:
      - notice
      responses:
        '200':
          description: Get all notices
  "/api/v1/users":
    get:
      summary: Get all user
      tags:
      - User
      responses:
        '200':
          description: Get all user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        email:
                          type: string
                        user_name:
                          type: string
                        role:
                          type: integer
                        first_name:
                          type: string
                        last_name:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        avatar:
                          type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
